apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alertmanager-application-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alertmanager-application-monitoring
subjects:
- kind: ServiceAccount
  name: alertmanager-service-account
  namespace: application-monitoring
userNames:
- system:serviceaccount:application-monitoring:alertmanager-service-account
