apiVersion: applicationmonitoring.integreatly.org/v1alpha1
kind: ApplicationMonitoring
metadata:
  name: example-applicationmonitoring
  namespace: application-monitoring
spec:
  labelSelector: "middleware"
  additionalScrapeConfigSecretName: "integreatly-additional-scrape-configs"
  additionalScrapeConfigSecretKey: "integreatly-additional.yaml"
  prometheusRetention: 15d
  prometheusStorageRequest: 10Gi
  prometheusInstanceNamespaces: application-monitoring
  alertmanagerInstanceNamespaces: application-monitoring
  selfSignedCerts: true
